### ISSUE TITLE
Add to documentation view 'Config BlueXolo using Docker'

### ISSUE THREAD

**Issue by capikp** [BlueXolo-Tools/DocumentationWebPage#16]
**Describe the feature**
	As a 'user/developer',
	I want to 'see topic with instructions to config BlueXolo using Docker' 
	so that I can 'config BlueXolo using Docker'

**Acceptance criteria**
	Given 'the user/developer'
	When 'search on documentation view'
	Then 'see topic with instructions to config BlueXolo using Docker'

**Comment by snvc00** [comment]
Waiting for BlueXolo youtube account credentials.
