### ISSUE TITLE
Add ZenHub icon link with its tooltip in Main Component module

### ISSUE THREAD

**Issue by Grixtli** [BlueXolo-Tools/DocumentationWebPage#2]

**Comment by Grixtli** [comment]
get icon to be displayed

**Comment by Grixtli** [comment]
@capikp can you help  to Luis on where to get the  icon?

**Comment by capikp** [comment]
Hi, in this task we need add a new icon for ZenHub on the header, the others icons was got of this library: https://fontawesome.com/

**Comment by filus-1** [comment]
Unfortunately the library doesn't contain any Zenhub related icons, so it's necessary to find a new source.

**Comment by filus-1** [comment]
Encontré un icono relacionado a Zenhub en el siguiente link https://iconify.design/icon-sets/logos/zenhub.html

**Comment by capikp** [comment]
I think the best solution is create the icon with css.

**Comment by capikp** [comment]
Hi, I think the this way, we can resolve this issue:

app.component.css

![image](https://user-images.githubusercontent.com/46430704/76580065-26603c80-6494-11ea-8e8c-590064212585.png)

app.component.html
![image](https://user-images.githubusercontent.com/46430704/76580105-57407180-6494-11ea-8746-87c5778b9124.png)

**Comment by capikp** [comment]
This is the result:

![image](https://user-images.githubusercontent.com/46430704/76580499-c9658600-6495-11ea-923a-3351c0e51f43.png)

**Comment by filus-1** [comment]
I decided to use a svg file to create the icon.

app.component.css

![image](https://user-images.githubusercontent.com/56836882/76588199-0a689500-64ac-11ea-8f55-03d495876742.png)

app.component.html

![image](https://user-images.githubusercontent.com/56836882/76588553-ec4f6480-64ac-11ea-94f1-d5d2bae329b2.png)

this being the result:

![image](https://user-images.githubusercontent.com/56836882/76588647-1ef95d00-64ad-11ea-8176-9427f499aa2d.png)

**Comment by filus-1** [comment]
#11

**Comment by filus-1** [comment]
The icon has been created from scratch by using an art app
