### ISSUE TITLE
Add Tooltips to slider buttoms 

### ISSUE THREAD

**Issue by Grixtli** [BlueXolo-Tools/DocumentationWebPage#4]

**Comment by Grixtli** [comment]
getting familiar with Angular, setting new BlueXolo  environment

**Comment by capikp** [comment]
In this issue we need add tooltips on slider buttons, such as on the google group button in the header. We can do it using matTooltip from Angular Material.

e.g.
matTooltip="Any comment"

**Comment by capikp** [comment]
The slider buttons are the next:

![image](https://user-images.githubusercontent.com/46430704/75612676-77af1a00-5aeb-11ea-99b2-31c56277ce02.png)
